name: Test
on:
  pull_request:
  workflow_dispatch:

jobs:

  test-windows:
    if: true # false to skip job during debug
    name: Test Python set up
    runs-on: windows-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Test
      run: |
        .\install-env.bat